name: mempool_project

profile: mempool_project

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  mempool_project:
    +schema: raw

models:
  mempool_project:
    staging:
      +materialized: view
